CREATE TABLE JOB_INSTANCE_STATUS (
  JOB_INSTANCE_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  PROCESS_INSTANCE_ID BIGINT DEFAULT NULL,
  PROCESS_INSTANCE_NAME VARCHAR(255) DEFAULT NULL,
  JOB_NAME VARCHAR(255) NOT NULL,
  JOB_PROJECT varchar(128),
  JOB_DISPLAY_NAME VARCHAR(255) DEFAULT NULL,
  JOB_GUID VARCHAR(100) NOT NULL,
  JOB_EXT_ID VARCHAR(255) DEFAULT NULL,
  JOB_INFO VARCHAR(255) DEFAULT NULL,
  ROOT_JOB_GUID VARCHAR(100) DEFAULT NULL,
  WORK_ITEM VARCHAR(1024) DEFAULT NULL,
  TIME_RANGE_START TIMESTAMP(3) NULL DEFAULT NULL,
  TIME_RANGE_END TIMESTAMP(3) NULL DEFAULT NULL,
  VALUE_RANGE_START VARCHAR(512) DEFAULT NULL,
  VALUE_RANGE_END VARCHAR(512) DEFAULT NULL,
  JOB_STARTED_AT TIMESTAMP(3) NULL DEFAULT NULL,
  JOB_ENDED_AT TIMESTAMP(3) NULL DEFAULT NULL,
  JOB_RESULT VARCHAR(1024) DEFAULT NULL,
  COUNT_INPUT INT(11) DEFAULT NULL,
  COUNT_OUTPUT INT(11) DEFAULT NULL,
  COUNT_UPDATED INT(11) DEFAULT NULL,
  COUNT_REJECTED INT(11) DEFAULT NULL,
  COUNT_DELETED INT(11) DEFAULT NULL,
  RETURN_CODE INT(11) DEFAULT NULL,
  RETURN_MESSAGE TEXT,
  HOST_NAME VARCHAR(255) DEFAULT NULL,
  HOST_PID INT(11) DEFAULT NULL,
  HOST_USER VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (JOB_INSTANCE_ID)
) DEFAULT CHARSET=UTF8;

CREATE INDEX JOB_INSTANCE_STATUS_JOB_GUID ON JOB_INSTANCE_STATUS(JOB_GUID);
CREATE INDEX JOB_INSTANCE_STATUS_JOB_NAME ON JOB_INSTANCE_STATUS(JOB_NAME);

CREATE TABLE JOB_INSTANCE_CONTEXT (
    JOB_INSTANCE_ID BIGINT NOT NULL,      -- reference to thr job instance
    ATTRIBUTE_KEY VARCHAR(100) NOT NULL,  -- context variable name
    ATTRIBUTE_VALUE VARCHAR(1024),        -- textual representation of the value
    ATTRIBUTE_TYPE VARCHAR(32) NOT NULL,  -- Java class name of the value to get it back in the correct format
    IS_OUTPUT_ATTR BOOLEAN NOT NULL);     -- 0 = Input, 1 = Output
    
CREATE INDEX JOB_INSTANCE_CONTEXT_IDX ON JOB_INSTANCE_CONTEXT(JOB_INSTANCE_ID, ATTRIBUTE_KEY, IS_OUTPUT_ATTR);

CREATE TABLE JOB_INSTANCE_COUNTERS (
    JOB_INSTANCE_ID BIGINT NOT NULL,     -- reference to the job instance
    COUNTER_NAME VARCHAR(128) NOT NULL,  -- name of the counter set in tJobInstanceEnd for a counter
    COUNTER_VALUE INTEGER,               -- value of the counter
    CONSTRAINT PK_JOB_INSTANCE_COUNTERS PRIMARY KEY (JOB_INSTANCE_ID, COUNTER_NAME));
    
CREATE TABLE JOB_INSTANCE_LOGS (
   JOB_INSTANCE_ID BIGINT NOT NULL,
   LOG_TS TIMESTAMP NOT NULL,
   LOG_LEVEL VARCHAR(10),
   LOG_NAME VARCHAR(128) NOT NULL,
   LOG_MESSAGE TEXT);

CREATE INDEX JOB_INSTANCE_LOGS_JOBID ON JOB_INSTANCE_LOGS(JOB_INSTANCE_ID);