-- drop table JOB_INSTANCE_STATUS;
CREATE TABLE JOB_INSTANCE_STATUS (
   JOB_INSTANCE_ID NUMBER(19) NOT NULL,
   PROCESS_INSTANCE_ID NUMBER(19),
   PROCESS_INSTANCE_NAME VARCHAR2(255),
   JOB_NAME VARCHAR2(255) NOT NULL,
   JOB_PROJECT VARCHAR2(128),
   JOB_INFO VARCHAR2(512),
   JOB_DISPLAY_NAME VARCHAR2(255),
   JOB_GUID VARCHAR2(100) NOT NULL,
   JOB_EXT_ID VARCHAR2(255),
   ROOT_JOB_GUID VARCHAR2(100),
   WORK_ITEM VARCHAR2(1024),
   TIME_RANGE_START TIMESTAMP,
   TIME_RANGE_END TIMESTAMP,
   VALUE_RANGE_START VARCHAR2(512),
   VALUE_RANGE_END VARCHAR2(512),
   JOB_STARTED_AT TIMESTAMP NOT NULL,
   JOB_ENDED_AT TIMESTAMP,
   JOB_RESULT VARCHAR2(1024),
   COUNT_INPUT INTEGER,
   COUNT_OUTPUT INTEGER,
   COUNT_UPDATED INTEGER,
   COUNT_REJECTED INTEGER,
   COUNT_DELETED INTEGER,
   RETURN_CODE INTEGER,
   RETURN_MESSAGE VARCHAR2(1024),
   HOST_NAME VARCHAR2(255),
   HOST_PID INTEGER,
   HOST_USER VARCHAR(128),
   CONSTRAINT JOB_INSTANCES_PKEY PRIMARY KEY (JOB_INSTANCE_ID));

CREATE INDEX JOB_INSTANCES_JOB_GUID ON JOB_INSTANCE_STATUS(JOB_GUID);
CREATE INDEX JOB_INSTANCES_JOB_NAME ON JOB_INSTANCE_STATUS(JOB_NAME);

CREATE SEQUENCE SEQ_JOB_INSTANCE_ID START WITH 1;

CREATE TABLE JOB_INSTANCE_CONTEXT (
    JOB_INSTANCE_ID NUMBER(19) NOT NULL,
    ATTRIBUTE_KEY VARCHAR2(255) NOT NULL,
    ATTRIBUTE_VALUE VARCHAR2(1024),
    ATTRIBUTE_TYPE VARCHAR2(32) NOT NULL,
    IS_OUTPUT_ATTR NUMBER(1) NOT NULL);
    
CREATE INDEX JOB_INSTANCES_CONTEXT_IDX ON JOB_INSTANCE_CONTEXT(JOB_INSTANCE_ID, IS_OUTPUT_ATTR, ATTRIBUTE_KEY);

CREATE TABLE JOB_INSTANCE_COUNTERS (
    JOB_INSTANCE_ID NUMBER(19) NOT NULL,
    COUNTER_NAME VARCHAR2(128) NOT NULL,
    COUNTER_VALUE INTEGER NOT NULL);
    
CREATE INDEX JOB_INSTANCE_COUNTERS_IDX ON JOB_INSTANCE_COUNTERS(JOB_INSTANCE_ID, COUNTER_NAME);

-- this table will be written from the Log4J appender in tJobInstanceStart
CREATE TABLE JOB_INSTANCE_LOGS (
    JOB_INSTANCE_ID NUMBER(19) NOT NULL,
    LOG_TS TIMESTAMP NOT NULL,
    LOG_LEVEL VARCHAR2(10) NOT NULL, -- INFO, DEBUG, WARN, ERROR
    LOG_NAME VARCHAR2(128) NOT NULL,
    LOG_MESSAGE CLOB);
	
CREATE INDEX JOB_INSTANCE_LOGS_JOBID ON JOB_INSTANCE_LOGS(JOB_INSTANCE_ID);