/* because of MySQL is per default case senstitive it is supposed to create the tables in uppercase letters to avoid any necessary configuration
   in the component tJobInstanceStart. This component expect the tables in uppercase letters
 */

-- This table keeps all job runs called job instances 
--DROP TABLE JOB_INSTANCES;
CREATE TABLE JOB_INSTANCES_TEST (
  PROZESS_ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  PROCESS_INSTANCE_ID BIGINT(20) DEFAULT NULL,
  PROCESS_INSTANCE_NAME VARCHAR(255) DEFAULT NULL,
  JOB_NAME VARCHAR(255) NOT NULL,
  JOB_DISPLAY_NAME VARCHAR(255) DEFAULT NULL,
  JOB_GUID VARCHAR(100) NOT NULL,
  JOB_EXT_ID VARCHAR(255) DEFAULT NULL,
  JOB_INFO VARCHAR(255) DEFAULT NULL,
  ROOT_JOB_GUID VARCHAR(100) DEFAULT NULL,
  WORK_ITEM VARCHAR(1024) DEFAULT NULL,
  TIME_RANGE_START TIMESTAMP NULL DEFAULT NULL,
  TIME_RANGE_END TIMESTAMP NULL DEFAULT NULL,
  VALUE_RANGE_START VARCHAR(512) DEFAULT NULL,
  VALUE_RANGE_END VARCHAR(512) DEFAULT NULL,
  JOB_STARTED_AT TIMESTAMP NULL DEFAULT NULL,
  JOB_ENDED_AT TIMESTAMP NULL DEFAULT NULL,
  JOB_RESULT VARCHAR(1024) DEFAULT NULL,
  COUNT_INPUT INT(11) DEFAULT NULL,
  COUNT_OUTPUT INT(11) DEFAULT NULL,
  COUNT_UPDATED INT(11) DEFAULT NULL,
  COUNT_REJECTED INT(11) DEFAULT NULL,
  COUNT_DELETED INT(11) DEFAULT NULL,
  RETURN_CODE INT(11) DEFAULT NULL,
  RETURN_MESSAGE TEXT,
  HOST_NAME VARCHAR(255) DEFAULT NULL,
  HOST_PID INT(11) DEFAULT NULL,
  HOST_USER VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (PROZESS_ID)
) DEFAULT CHARSET=UTF8;

CREATE INDEX JOB_INSTANCES_JOB_GUID ON JOB_INSTANCES_TEST(JOB_GUID);

--DROP TABLE JOB_INSTANCE_CONTEXT;
CREATE TABLE JOB_INSTANCE_CONTEXT (
    PROZESS_ID BIGINT NOT NULL, -- reference to thr job instance
    ATTRIBUTE_KEY VARCHAR(100) NOT NULL,  -- context variable name
    ATTRIBUTE_STRING_VALUE VARCHAR(1024), -- textual representation of the value
    ATTRIBUTE_TYPE VARCHAR(32) NOT NULL,  -- Java class name of the value to get it back in the correct format
    IS_OUTPUT_ATTR BOOLEAN NOT NULL);     -- 0 = Input, 1 = Output
    
CREATE INDEX JOB_INSTANCE_CONTEXT_IDX ON JOB_INSTANCE_CONTEXT(PROZESS_ID, ATTRIBUTE_KEY, IS_OUTPUT_ATTR);

--DROP TABLE JOB_INSTANCE_COUNTERS;
CREATE TABLE JOB_INSTANCE_COUNTERS (
    PROZESS_ID BIGINT NOT NULL,  -- reference to the job instance
    COUNTER_NAME VARCHAR(128) NOT NULL,  -- name of the counter set in tJobInstanceEnd for a counter
    COUNTER_VALUE INTEGER,            -- value of the counter
    CONSTRAINT PK_JOB_INSTANCE_COUNTERS PRIMARY KEY (PROZESS_ID, COUNTER_NAME));
    
/* for future use, it should be used e.g. for Log4J based loggers
*/
--DROP TABLE JOB_INSTANCE_LOGS;
CREATE TABLE JOB_INSTANCE_LOGS (
   PROZESS_ID BIGINT NOT NULL,
   LOG_TS TIMESTAMP NOT NULL,
   LOG_LEVEL VARCHAR(10),
   LOG_NAME VARCHAR(128) NOT NULL,
   LOG_MESSAGE TEXT);

CREATE INDEX JOB_INSTANCE_LOGS_JOBID ON JOB_INSTANCE_LOGS(PROZESS_ID);